-- db.sql
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
    CREATE TYPE order_status AS ENUM ('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'CANCELED');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method') THEN
    CREATE TYPE payment_method AS ENUM ('COD', 'TRANSFER', 'CARD', 'OTHER');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS categories ( category TEXT PRIMARY KEY );
INSERT INTO categories(category) VALUES
('Gà'),('Vịt'),('Combo'),('Món kèm'),('Giải khát')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS products (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  category    TEXT NOT NULL REFERENCES categories(category) ON UPDATE CASCADE,
  price_sell  INTEGER NOT NULL CHECK (price_sell >= 0),
  price_cost  INTEGER NOT NULL CHECK (price_cost >= 0),
  unit        TEXT NOT NULL,
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  image_url   TEXT,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_active   ON products(active);

CREATE TABLE IF NOT EXISTS orders (
  id             TEXT PRIMARY KEY,
  status         order_status NOT NULL,
  customer_name   TEXT,
  customer_phone  TEXT,
  customer_address TEXT,
  payment_method payment_method NOT NULL,
  subtotal     INTEGER NOT NULL CHECK (subtotal >= 0),
  discount     INTEGER NOT NULL CHECK (discount >= 0),
  total        INTEGER NOT NULL CHECK (total >= 0),
  cost_total   INTEGER NOT NULL CHECK (cost_total >= 0),
  profit       INTEGER NOT NULL,
  promo_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  meta           JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_customer_phone ON orders(customer_phone);

CREATE TABLE IF NOT EXISTS order_items (
  order_id   TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  line_no    INTEGER GENERATED BY DEFAULT AS IDENTITY,
  product_id TEXT,
  name       TEXT NOT NULL,
  price_sell INTEGER NOT NULL CHECK (price_sell >= 0),
  price_cost INTEGER NOT NULL CHECK (price_cost >= 0),
  qty        INTEGER NOT NULL CHECK (qty > 0),
  PRIMARY KEY (order_id, line_no)
);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id);

CREATE TABLE IF NOT EXISTS config (
  id            BOOLEAN PRIMARY KEY DEFAULT TRUE,
  promo_active  BOOLEAN NOT NULL,
  promo_percent INTEGER NOT NULL CHECK (promo_percent BETWEEN 0 AND 100)
);
INSERT INTO config (id, promo_active, promo_percent)
VALUES (TRUE, TRUE, 10) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS settings_promo (
  id       BOOLEAN PRIMARY KEY DEFAULT TRUE,
  enabled  BOOLEAN NOT NULL,
  percent  INTEGER NOT NULL CHECK (percent BETWEEN 0 AND 100),
  start_at TIMESTAMPTZ,
  end_at   TIMESTAMPTZ
);
INSERT INTO settings_promo (id, enabled, percent, start_at, end_at)
VALUES (TRUE, FALSE, 100, NULL, NULL) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS push_subscriptions (
  endpoint        TEXT PRIMARY KEY,
  expiration_time TIMESTAMPTZ,
  key_p256dh      TEXT NOT NULL,
  key_auth        TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_products_updated_at') THEN
    CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_orders_updated_at') THEN
    CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE OR REPLACE VIEW v_orders_with_items AS
SELECT
  o.id,
  o.status,
  jsonb_build_object(
    'name',    o.customer_name,
    'phone',   o.customer_phone,
    'address', o.customer_address
  ) AS customer,
  o.payment_method,
  (
    SELECT jsonb_agg(jsonb_build_object(
      'productId',  oi.product_id,
      'name',       oi.name,
      'priceSell',  oi.price_sell,
      'priceCost',  oi.price_cost,
      'qty',        oi.qty
    ) ORDER BY oi.line_no)
    FROM order_items oi WHERE oi.order_id = o.id
  ) AS items,
  o.subtotal, o.discount, o.total, o.cost_total, o.profit,
  o.promo_snapshot, o.meta, o.created_at, o.updated_at
FROM orders o;

CREATE OR REPLACE VIEW v_products AS
SELECT id, name, category,
       price_sell AS "priceSell",
       price_cost AS "priceCost",
       unit, active,
       image_url AS "imageUrl",
       description,
       created_at AS "createdAt",
       updated_at AS "updatedAt"
FROM products;
